name: open_data_hub_mobile_app
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  auto_size_text: 3.0.0
  cached_network_image: 3.4.1
  cached_network_image_platform_interface: 4.1.1
  cached_network_image_web: 1.3.1
  cloud_firestore: ^6.1.2
  cloud_firestore_platform_interface: ^7.0.6
  cloud_firestore_web: ^5.1.2
  collection: 1.19.1
  firebase_core: ^4.4.0
  firebase_core_platform_interface: ^6.0.2
  firebase_core_web: ^3.4.0
  firebase_performance: ^0.11.1+4
  firebase_performance_platform_interface: ^0.1.6+4
  firebase_performance_web: ^0.1.8+2
  flutter_animate: ^4.5.2
  flutter_cache_manager: 3.4.1
  font_awesome_flutter: ^10.12.0
  from_css_color: 2.0.0
  go_router: ^17.0.1
  google_fonts: ^7.0.2
  intl: 0.20.2
  json_path: ^0.9.0
  page_transition: ^2.2.1
  path_provider: ^2.1.5
  path_provider_android: ^2.2.22
  path_provider_foundation: ^2.6.0
  path_provider_linux: 2.2.1
  path_provider_platform_interface: 2.1.2
  path_provider_windows: 2.3.0
  plugin_platform_interface: 2.1.8
  provider: ^6.1.5+1
  shared_preferences: ^2.5.4
  shared_preferences_android: ^2.4.18
  shared_preferences_foundation: ^2.5.6
  shared_preferences_linux: 2.4.1
  shared_preferences_platform_interface: 2.4.1
  shared_preferences_web: 2.4.3
  shared_preferences_windows: 2.4.1
  sqflite: ^2.4.2
  sqflite_common: ^2.5.6
  stream_transform: ^2.1.1
  timeago: 3.7.1
  url_launcher: ^6.3.2
  url_launcher_android: ^6.3.28
  url_launcher_ios: ^6.3.6
  url_launcher_linux: ^3.2.2
  url_launcher_macos: ^3.2.5
  url_launcher_platform_interface: 2.3.2
  url_launcher_web: ^2.4.2
  url_launcher_windows: ^3.1.5
  flutter_dotenv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
